### ISSUE TITLE
Container instances do not cache

### ISSUE THREAD

**Issue by mayuanyang** [introtocomputerscience/azure-function-autofac-dependency-injection#59] opened 2020-11-23 05:09 UTC
**Is your feature request related to a problem? Please describe.**
Hi there, thanks for your work, just wondering if you have any plan to not to have container instances cached? I am looking for a brand new container every time a function triggered. Thanks

**Comment by rawrspace** [comment] 2020-11-23 05:11
That should be happening. Do you have a sample project that shows the caching behavior?

As far as I recall the function reuses the container but separate function invocations should get new containers.

**Comment by mayuanyang** [comment] 2020-11-23 05:17
Attached is how i used, the function triggered by a scheduler every minute, container seems get reused which could lead to problem.

Looks like container get cached from here?
https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/c51d6bdf06ee5b404eb35a87a1073464d1f4cad8/AzureFunctions.Autofac.Shared/Configuration/DependencyInjection.cs#L27 

```
[DependencyInjectionConfig(typeof(DependencyInjectionConfiguration))]
    public static class ScheduleCalculateMerchFoodLike
    {
        [FunctionName("ScheduleCalculateXXX")]
        public static async Task Run([TimerTrigger("%CALCULATE_XXX_SCHEDULE%")]TimerInfo myTimer,
            [Inject]IMediator mediator)
        {
             await mediator.SendAsync(new CalculateXXXCommand());
        }
    }
```

**Comment by rawrspace** [comment] 2020-11-23 05:20
I'll check it out tomorrow. That caching should only be the lifetime of the single function invocation.

Each function invocation should create a new dependency injection config which would result in a new concurrent dictionary.

**Comment by mayuanyang** [comment] 2020-11-23 05:37
Yup, this happens within the same function, as my function run every 1 minute and sometimes it took more than 1 minute to finish, e.g the current function is still in running state and another call of the same function jumps in, same container is shared

**Comment by rawrspace** [comment] 2020-11-23 15:13
I am investigating this issue currently. Is the IMediator in your example registered as a singleton?

Currently if I run a timer triggered function then as you can see [here](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/c51d6bdf06ee5b404eb35a87a1073464d1f4cad8/AzureFunctions.Autofac.Shared/Configuration/DependencyInjection.cs#L28) the instances are getting their own instance of the container.

However when I made the registered type a singleton instead of transient I saw the caching behavior since that container was giving the same instance to every instance container.

The sample project I am using is [here](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/tree/feature/optional-caching). I made a timer triggered and http triggered function to test. Without adding ".SingleInstance()" to the end of the registration in the CachingConfig.cs I do not see the behavior you described.

I need more information on your setup to pursue this further.

**Comment by mayuanyang** [comment] 2020-11-23 23:18
It is a InstancePerLifetime scope

**Comment by rawrspace** [comment] 2020-11-23 23:19
Can you share an example project? I shared my branch where I was unable to reproduce it.

**Comment by mayuanyang** [comment] 2020-11-24 06:04
Let assume that i have a micro service A, A sends messages to Azure Function via service bus, in this sample `SayHelloCommand`, IMediator is being injected to handle the command, and the system will take 50 seconds to handle this message

At 00:00:01, A sends a command to the function, an IMediator is resolved with scope1
At 00:00:05 A sends another instance of the same command to the function, at this points, IIRIC as the scope1 still in the ConcurrentDictionary, GetOrAdd will get the existing one from the dictionary and return, as IMediator is instance per lifetime, so same IMediator instance is returned.

Is it right?

```
[FunctionName("ConsumeHelloCommand")]
            public static async Task Run(
            [ServiceBusTrigger("TopicName", "QueueName", Connection = "AzureWebJobsServiceBus")]string mySbMsg, 
            [Inject]IMediator mediator)
        {
            await mediator.SendByMediator<SayHelloCommand>(mySbMsg);
        }
```

**Comment by rawrspace** [comment] 2020-11-24 11:44
No because the instance container is resolved by function id which is unique per function invocation. The container itself would be shared but the code starts a new lifetime scope per function invocation. That is the code I reference on line 28 https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/c51d6bdf06ee5b404eb35a87a1073464d1f4cad8/AzureFunctions.Autofac.Shared/Configuration/DependencyInjection.cs#L28

The only way I was able to make this occur was by registering the type as a single instance which result in it being shared.

If you can share a project with steps on how to replicate the issue I would be happy to look into this further. Without that I am at a dead end.

**Comment by mayuanyang** [comment] 2020-11-24 11:54
Here is the project that how IMediator being registered in Autofac https://github.com/mayuanyang/Mediator.Net/blob/8b1f3a2e2e22cac03a237cc219e401e73c9c6329/src/Mediator.Net.Autofac/ContainerBuilderExtensions.cs#L9

**Comment by rawrspace** [comment] 2020-11-24 12:20
That appears to be a relatively complex project but I will take a look later today. I'm suspicious of the mediator builder being registered as a single instance. I did not see a test for this case you're describing so I will see if I can create a test case in that project to verify the issue. If a test case already exists please let me know. If not can you give me the steps using that project to reproduce the behavior?

**Comment by rawrspace** [comment] 2020-11-24 13:38
I don't see an azure functions sample project in that repository. Did you have an azure functions example project that is exhibiting the issues?

Thanks.

**Comment by mayuanyang** [comment] 2020-11-24 14:11
Hi, no azure function from that project cause it is a private project hosting on a company's repo, however the codes are similar to the sample that i pasted. `MediatorBuilder` will return a new instance of `IMediator` every time the `Build` is called, it then get registered in `Autofac`  with the scope of InstancePerLifetime 

Thanks

**Comment by rawrspace** [comment] 2020-11-24 14:24
Can you put together a small sample project that recreates the issue? 

I am not familiar with that package but I put together an Azure functions example called caching-example in the branch https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/tree/feature/optional-caching that is not showing that behavior when using both timer based and http based functions.

For time based functions it is not running them concurrently. For example if I start a function at time 0 that runs every 5 seconds but takes 10 seconds to run the next one is not triggered until time 10 when the first completes. This is by design for azure functions. So instead I created an HTTP based function I could hit twice within the time limit and still in that case it gets a separate container for each instance since they have different function invocation ids.

The only way I can make the sharing happen is by marking something as SingleInstance. In the code you shared I see the MediatorBuilder is a single instance so I wonder if that perhaps is the source of the issue. Have you tried changing that to instead be transient or lifetime scoped instead of single instance?

**Comment by rawrspace** [comment] 2020-11-24 14:31
I could make it so there is a parameter to disable caching and that would make it so that the container is always only associated only with the function ID.

This would mean that instead of using the container from the [concurrent dictionary](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/c51d6bdf06ee5b404eb35a87a1073464d1f4cad8/AzureFunctions.Autofac.Shared/Configuration/DependencyInjection.cs#L27) it would just make a new container for each function invocation.

Would that achieve what you are trying to accomplish? I can put out a alpha package if you wanted to test it.

**Comment by rawrspace** [comment] 2020-11-24 15:39
Can you try upgrading to [4.02-alpha](https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.2-alpha) in your project and then [set enable caching](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/feature/optional-caching/README.md#container-caching) to false?

Please let me know if this resolves your issue.

When I tested this with the [caching-example](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/tree/feature/optional-caching/caching-example) project you can see the `[Cache Enabled]` entries have the same Guid and the `[Cache Disabled]` entries all have unique Guids:
```
Azure Functions Core Tools
Core Tools Version:       3.0.2996 Commit hash: c54cdc36323e9543ba11fb61dd107616e9022bba
Function Runtime Version: 3.0.14916.0


Functions:

        CachingDisabled: timerTrigger

        CachingEnabled: timerTrigger

For detailed output, run func with --verbose flag.
[2020-11-24T15:12:45.201Z] Executing 'CachingDisabled' (Reason='Timer fired at 2020-11-24T09:12:45.0265708-06:00', Id=8b00647f-99d0-4fdd-ba89-ad9d2453c80c)
[2020-11-24T15:12:45.201Z] Executing 'CachingEnabled' (Reason='Timer fired at 2020-11-24T09:12:45.0265717-06:00', Id=1d306b2d-5df6-46c8-9427-b24dc36914ea)
[2020-11-24T15:12:49.291Z] Host lock lease acquired by instance ID '0000000000000000000000002DE397AF'.
[2020-11-24T15:12:52.251Z] [Cache Disabled]At 11/24/2020 9:12:45 AM we got c04c2549-645a-42ec-9c0d-b6973b8a92ac
[2020-11-24T15:12:52.251Z] [Cache Enabled]At 11/24/2020 9:12:45 AM we got 469c787c-155a-4c98-81f2-394ba55131c8
[2020-11-24T15:12:52.304Z] Executed 'CachingEnabled' (Succeeded, Id=1d306b2d-5df6-46c8-9427-b24dc36914ea, Duration=7253ms)
[2020-11-24T15:12:52.304Z] Executed 'CachingDisabled' (Succeeded, Id=8b00647f-99d0-4fdd-ba89-ad9d2453c80c, Duration=7253ms)
[2020-11-24T15:12:52.390Z] Executing 'CachingEnabled' (Reason='Timer fired at 2020-11-24T09:12:52.3886531-06:00', Id=fcee4437-e52c-4cdc-a0c3-56e182a54a94)
[2020-11-24T15:12:52.401Z] Executing 'CachingDisabled' (Reason='Timer fired at 2020-11-24T09:12:52.3886264-06:00', Id=908ea1d0-f1eb-4fac-9877-f51d15e845a2)
[2020-11-24T15:12:59.398Z] [Cache Enabled]At 11/24/2020 9:12:52 AM we got 469c787c-155a-4c98-81f2-394ba55131c8
[2020-11-24T15:12:59.405Z] Executed 'CachingEnabled' (Succeeded, Id=fcee4437-e52c-4cdc-a0c3-56e182a54a94, Duration=7015ms)
[2020-11-24T15:12:59.410Z] [Cache Disabled]At 11/24/2020 9:12:52 AM we got 79eb4670-559a-466b-a3cd-608ce0bf280a
[2020-11-24T15:12:59.416Z] Executed 'CachingDisabled' (Succeeded, Id=908ea1d0-f1eb-4fac-9877-f51d15e845a2, Duration=7027ms)
[2020-11-24T15:12:59.429Z] Executing 'CachingEnabled' (Reason='Timer fired at 2020-11-24T09:12:59.4279544-06:00', Id=d5c1c323-f4ab-42f8-93a3-3e358e79849b)
[2020-11-24T15:12:59.430Z] Executing 'CachingDisabled' (Reason='Timer fired at 2020-11-24T09:12:59.4279544-06:00', Id=06025a9f-79e9-4cac-9bba-da497b7241eb)
[2020-11-24T15:13:06.453Z] [Cache Disabled]At 11/24/2020 9:12:59 AM we got 17cb8a50-c96b-44e8-b67a-2067ea182416
[2020-11-24T15:13:06.453Z] [Cache Enabled]At 11/24/2020 9:12:59 AM we got 469c787c-155a-4c98-81f2-394ba55131c8
[2020-11-24T15:13:06.458Z] Executed 'CachingDisabled' (Succeeded, Id=06025a9f-79e9-4cac-9bba-da497b7241eb, Duration=7030ms)
[2020-11-24T15:13:06.462Z] Executed 'CachingEnabled' (Succeeded, Id=d5c1c323-f4ab-42f8-93a3-3e358e79849b, Duration=7034ms)
[2020-11-24T15:13:06.476Z] Executing 'CachingDisabled' (Reason='Timer fired at 2020-11-24T09:13:06.4741172-06:00', Id=9829dc8a-e6bc-40b2-b6a1-45d7a0ab8849)
[2020-11-24T15:13:06.498Z] Executing 'CachingEnabled' (Reason='Timer fired at 2020-11-24T09:13:06.4974522-06:00', Id=1e478194-de6a-41b5-a121-979325bb5e39)
[2020-11-24T15:13:13.489Z] [Cache Disabled]At 11/24/2020 9:13:06 AM we got 705bd3d1-4938-4724-853a-2c52efaf1c5c
[2020-11-24T15:13:13.495Z] Executed 'CachingDisabled' (Succeeded, Id=9829dc8a-e6bc-40b2-b6a1-45d7a0ab8849, Duration=7021ms)
[2020-11-24T15:13:13.506Z] Executing 'CachingDisabled' (Reason='Timer fired at 2020-11-24T09:13:13.5040275-06:00', Id=cb241f7a-0f07-4879-bbca-a5acafe6ed89)
[2020-11-24T15:13:13.519Z] [Cache Enabled]At 11/24/2020 9:13:06 AM we got 469c787c-155a-4c98-81f2-394ba55131c8
[2020-11-24T15:13:13.528Z] Executed 'CachingEnabled' (Succeeded, Id=1e478194-de6a-41b5-a121-979325bb5e39, Duration=7030ms)
[2020-11-24T15:13:13.551Z] Executing 'CachingEnabled' (Reason='Timer fired at 2020-11-24T09:13:13.5504871-06:00', Id=9c24006b-7197-4643-bc51-5c763324c362)
```

**Comment by mayuanyang** [comment] 2020-11-25 05:33
Hi!, really appreciate your help, will try it out soon. For curiosity, is your test based on a Azure Function Consumption plan or Premium?

**Comment by rawrspace** [comment] 2020-11-25 11:48
Local testing. I was not able to replicate your issue exactly but I had an idea of what was causing it which is what this solution is based on. I'll need your help to confirm of it fixed the issue though.

**Comment by rawrspace** [comment] 2020-12-07 15:16
@mayuanyang Have you had an opportunity to test this?

**Comment by rawrspace** [comment] 2020-12-08 12:49
Enhancement has been implemented and tested

**Closed as completed** 2020-12-08 12:49 UTC
Labels: enhancement, testing fix
