### ISSUE TITLE
"A second operation started on this context before a previous asynchronous operation completed"

### ISSUE THREAD

**Issue by fmesko** [introtocomputerscience/azure-function-autofac-dependency-injection#41] opened 2019-06-02 16:06 UTC
I am using [AzureFunctions.Autofac](https://www.nuget.org/packages/AzureFunctions.Autofac) to inject into my Azure Functions web api. An example of the config:

```csharp
  public class DIConfig
    {
        public DIConfig()
        {
            DependencyInjection.Initialize(builder =>
            {
                // DAL
                builder.Register<IDbContext>(c => new SecretCompanyContext()).InstancePerLifetimeScope();
                builder.RegisterType<SecretCompanyContext>().InstancePerLifetimeScope();
                builder.RegisterType<SecretCompanyContext>().As<ICartContext>().InstancePerLifetimeScope();
                builder.RegisterGeneric(typeof(Repository<>)).As(typeof(IRepository<>)).InstancePerLifetimeScope();

                // Services               
                builder.RegisterType<InventoryServices>().As<IInventoryServices>().InstancePerLifetimeScope();

                // Controllers ported from ASP.NET MVC Web API
                builder.RegisterType<InventoryController>().InstancePerLifetimeScope();
            });
        }
```

Then my Azure functions, I have one class that defines all methods in the API

```csharp
    [DependencyInjectionConfig(typeof(DIConfig))]
    public class InventoryFunctions : FunctionsApi
    {
        [FunctionName("GetProductsByCategory")]
        // /inventory/categories/{id}/products
        public static async Task<HttpResponseMessage> GetProductsByCategory(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "inventory/categories/{id}/products")]
            HttpRequestMessage req,
            TraceWriter log,
            int id,
            [Inject] InventoryController controller)
        {
            // do stuff
            var result = await controller.GetProductsByCategory(id);
            return JsonResponse(result, HttpStatusCode.OK);
        }

        [FunctionName("GetInventoryBySku")]
        // /inventory/skus?sku=ASDF&sku=ASDG&sku=ASDH
        public static async Task<HttpResponseMessage> GetInventoryBySku(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "inventory")]
            HttpRequestMessage req,
            TraceWriter log,
            [Inject] InventoryController controller)
        {
            // do stuff
            var result = await controller.QueryInventoryBySkuList(skuList);
            return JsonResponse(result, HttpStatusCode.OK);
        }

        [FunctionName("UpdateProductsQuantity")]
        // /inventory
        // Post
        public static async Task<HttpResponseMessage> UpdateProductsQuantity(
            [HttpTrigger(AuthorizationLevel.Function, "put", Route = "inventory")]
            HttpRequestMessage req,
            TraceWriter log,
            [Inject] InventoryController controller)
        {
            // do stuff
            var inventoryProducts = await req.Content.ReadAsAsync<List<InvProductOperation>>();
            var result = await controller.UpdateAvailableProductsQuantity(inventoryProducts);
            return JsonResponse(result, HttpStatusCode.OK);
        }
```

But I keep getting this error:

> A second operation started on this context before a previous 
asynchronous operation completed. Use 'await' to ensure that 
any asynchronous operations have completed before calling 
another method on this context. Any instance members are not 
guaranteed to be thread safe. 

I have verified that `async` and `await` are used properly, so following the error message's recommendation isn't fixing it. What appears to be the issue is that `IDbContext` is not honoring the `InstancePerLifetimeScope` as expected. Is this happening because I have more than one method in my `InventoryFunctions` class? Or is AzureFunctions.Autofac not threadsafe?

**Comment by rawrspace** [comment] 2019-06-02 16:34
Can you provide a reproduction project that I can investigate?

**Comment by lorddev** [comment] 2019-06-02 16:38
Sorry, the repo in question is private. InstancePerLifetimeScope doesn't seem to be working. Should we add locks on each function to avoid threading issues or are we not doing the configuration properly?

**Comment by rawrspace** [comment] 2019-06-02 16:56
Are you able to create a minimal reproduction project? If you can I can take a look at this to resolve more quickly. 

At this point I can't advise if you are doing it correctly. The functionality you are referencing was added through a PR recently and likely was not thoroughly tested for your use case.

**Comment by lorddev** [comment] 2019-06-02 17:10
If I were to create a minimalist reproduction project it would basically include the two code snippets above and nothing else. Reproducing the error requires a lot of traffic happening at the same time. Do you have recommendations for how I would reproduce it by calling it simultaneously from multiple threads? Maybe I would run the function locally using the tools and have a multithreaded unit test that calls it via localhost? How do I synchronize the unit test threads to make sure they call at exactly the same time? Thanks.

**Comment by rawrspace** [comment] 2019-06-02 17:20
I would create two projects. The first would be a reproduction project and the second would be a command line program that calls the first in parallel as many times as you want, essentially a load test. If you can provide that first project for me then I can do the command line program.

**Comment by lorddev** [comment] 2019-06-02 18:07
Here it is: https://github.com/lorddev/autofac-bug-repro

I still need to add the EF code-first seed.

**Comment by rawrspace** [comment] 2019-06-02 18:11
Thanks! I'll try to have a look tonight after I get my kids to sleep.

**Comment by lorddev** [comment] 2019-06-03 18:23
@vandersmissenc I changed it to `InstancePerDependency()` and that seems to have helped. Is this an ok workaround or is it less than ideal?

**Comment by lorddev** [comment] 2019-06-03 19:38
Never mind. The exceptions are still happening.

**Comment by rawrspace** [comment] 2019-06-04 01:22
Sorry for the delayed response. We are transitioning my 2 year old off of a binky and she was having none of it last night.

I forked the repro project to [my repo](https://github.com/vandersmissenc/autofac-bug-repro)

I had a bit of trouble getting the database seed to work but after I manually created it and added the products I was able to run the project and hit **GetInventoryBySku** with **TP001** and **TP002**

To test if the _InstancePerLifetimeScope_ functionality was working I added an internal ID field that is initialized with `Guid.NewGuid()` on the DB context and exposed upward (this has been pushed to my fork repo if you want to check it out) and each time the function executes it prints out the internal ID.

I started the program and ran that method 3 times and you will notice in the attached log that the line "**Internal Id: 4fae9d60-c0ac-4df3-870a-c4a9e9f91d0b**" appears 3 times. This indicates that the same instance of dbcontext is being provided each time that the function executes.

I noticed in the repro project that you are referencing v2.0 of AzureFunctions.Autofac. Is there a reason you haven't moved to the latest version? (I don't necessarily expect this to fix your issue but it is worth a shot)

**Can you provide me step by step instructions to recreate the error you were seeing? I have not been able to create it myself as I am likely not performing the same actions as you.** 

Here is the log:
```code

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

[6/4/2019 1:09:55 AM] Secrets manager initialized, repository type: Microsoft.Azure.WebJobs.Script.WebHost.FileSystemSecretsRepository
Listening on http://localhost:7071/
Hit CTRL-C to exit...
[6/4/2019 1:09:55 AM] Reading host configuration file 'C:\Users\vande\source\repos\autofac-bug-repro\src\AutofacBugRepro\bin\Debug\net471\host.json'
[6/4/2019 1:09:55 AM] Host configuration file read:
[6/4/2019 1:09:55 AM] {}
[6/4/2019 1:09:55 AM] Starting Host (HostId=desktopjh2dvk0-1270579546, Version=1.0.12491.0, InstanceId=9d06e32c-3b6e-4720-a9e5-7dd11db5cbe6, ProcessId=916, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[6/4/2019 1:09:56 AM] Loaded custom extension 'BotFrameworkConfiguration'
[6/4/2019 1:09:56 AM] Loaded custom extension 'SendGridConfiguration'
[6/4/2019 1:09:56 AM] Loaded custom extension 'EventGridExtensionConfig'
[6/4/2019 1:09:56 AM] Loaded binding extension 'InjectExtensionConfigProvider' from 'referenced by: Method='AutofacBugRepro.InventoryFunctions.SubtractProductsQuantity', Parameter='controller'.'
[6/4/2019 1:09:56 AM] Host keys are loaded.
[6/4/2019 1:09:56 AM] registered EventGrid Endpoint = http://localhost:7071/admin/extensions/EventGridExtensionConfig
[6/4/2019 1:09:56 AM] Generating 5 job function(s)
[6/4/2019 1:09:56 AM] Found the following functions:
[6/4/2019 1:09:56 AM] AutofacBugRepro.InventoryFunctions.GetProductCategories
[6/4/2019 1:09:56 AM] Host lock lease acquired by instance ID '0000000000000000000000001B8F1FC2'.
[6/4/2019 1:09:56 AM] AutofacBugRepro.InventoryFunctions.GetProductsByCategory
[6/4/2019 1:09:56 AM] AutofacBugRepro.InventoryFunctions.GetInventoryBySku
[6/4/2019 1:09:56 AM] AutofacBugRepro.InventoryFunctions.UpdateProductsQuantity
[6/4/2019 1:09:56 AM] AutofacBugRepro.InventoryFunctions.SubtractProductsQuantity
[6/4/2019 1:09:56 AM]
[6/4/2019 1:09:56 AM] Host initialized (745ms)
[6/4/2019 1:09:56 AM] Host started (757ms)
[6/4/2019 1:09:56 AM] Job host started
[6/4/2019 1:09:56 AM] Executing HTTP request: {
[6/4/2019 1:09:56 AM]   "requestId": "f103a144-63e5-4576-98a9-bfd9196593e8",
[6/4/2019 1:09:56 AM]   "method": "GET",
[6/4/2019 1:09:56 AM]   "uri": "/"
[6/4/2019 1:09:56 AM] }
[6/4/2019 1:09:56 AM] Executed HTTP request: {
[6/4/2019 1:09:56 AM]   "requestId": "f103a144-63e5-4576-98a9-bfd9196593e8",
[6/4/2019 1:09:56 AM]   "method": "GET",
[6/4/2019 1:09:56 AM]   "uri": "/",
[6/4/2019 1:09:56 AM]   "authorizationLevel": "Anonymous",
[6/4/2019 1:09:56 AM]   "status": "OK"
[6/4/2019 1:09:56 AM] }

Http Functions:

        GetInventoryBySku: http://localhost:7071/api/inventory

        GetProductCategories: http://localhost:7071/api/inventory/categories

        GetProductsByCategory: http://localhost:7071/api/inventory/categories/{id}/products

        SubractProductsQuantity: http://localhost:7071/api/inventory/subtract

        UpdateProductsQuantity: http://localhost:7071/api/inventory

Debugger listening on [::]:5858
[6/4/2019 1:09:59 AM] Executing HTTP request: {
[6/4/2019 1:09:59 AM]   "requestId": "fb5feda3-a86e-496d-acee-4325bb345c57",
[6/4/2019 1:09:59 AM]   "method": "GET",
[6/4/2019 1:09:59 AM]   "uri": "/api/inventory"
[6/4/2019 1:09:59 AM] }
[6/4/2019 1:09:59 AM] Function started (Id=b2eb5ba2-a45a-401c-82cf-0cd3bb6ec4c9)
[6/4/2019 1:10:00 AM] Executing 'GetInventoryBySku' (Reason='This function was programmatically called via the host APIs.', Id=b2eb5ba2-a45a-401c-82cf-0cd3bb6ec4c9)
[6/4/2019 1:10:00 AM] C# HTTP trigger function (GetInventoryBySku received a request.
[6/4/2019 1:10:00 AM] Internal Id: 4fae9d60-c0ac-4df3-870a-c4a9e9f91d0b
[6/4/2019 1:10:01 AM] Function completed (Success, Id=b2eb5ba2-a45a-401c-82cf-0cd3bb6ec4c9, Duration=1477ms)
[6/4/2019 1:10:01 AM] Executed 'GetInventoryBySku' (Succeeded, Id=b2eb5ba2-a45a-401c-82cf-0cd3bb6ec4c9)
[6/4/2019 1:10:01 AM] Executed HTTP request: {
[6/4/2019 1:10:01 AM]   "requestId": "fb5feda3-a86e-496d-acee-4325bb345c57",
[6/4/2019 1:10:01 AM]   "method": "GET",
[6/4/2019 1:10:01 AM]   "uri": "/api/inventory",
[6/4/2019 1:10:01 AM]   "authorizationLevel": "Anonymous",
[6/4/2019 1:10:01 AM]   "status": "OK"
[6/4/2019 1:10:01 AM] }
[6/4/2019 1:10:03 AM] Executing HTTP request: {
[6/4/2019 1:10:03 AM]   "requestId": "4dfc3cf7-fc54-4477-89d8-ffe82cf50b36",
[6/4/2019 1:10:03 AM]   "method": "GET",
[6/4/2019 1:10:03 AM]   "uri": "/api/inventory"
[6/4/2019 1:10:03 AM] }
[6/4/2019 1:10:03 AM] Function started (Id=1cc6f041-d5e7-424e-8341-e025bbe2052a)
[6/4/2019 1:10:03 AM] Executing 'GetInventoryBySku' (Reason='This function was programmatically called via the host APIs.', Id=1cc6f041-d5e7-424e-8341-e025bbe2052a)
[6/4/2019 1:10:03 AM] C# HTTP trigger function (GetInventoryBySku received a request.
[6/4/2019 1:10:03 AM] Internal Id: 4fae9d60-c0ac-4df3-870a-c4a9e9f91d0b
[6/4/2019 1:10:03 AM] Function completed (Success, Id=1cc6f041-d5e7-424e-8341-e025bbe2052a, Duration=11ms)
[6/4/2019 1:10:03 AM] Executed 'GetInventoryBySku' (Succeeded, Id=1cc6f041-d5e7-424e-8341-e025bbe2052a)
[6/4/2019 1:10:03 AM] Executed HTTP request: {
[6/4/2019 1:10:03 AM]   "requestId": "4dfc3cf7-fc54-4477-89d8-ffe82cf50b36",
[6/4/2019 1:10:03 AM]   "method": "GET",
[6/4/2019 1:10:03 AM]   "uri": "/api/inventory",
[6/4/2019 1:10:03 AM]   "authorizationLevel": "Anonymous",
[6/4/2019 1:10:03 AM]   "status": "OK"
[6/4/2019 1:10:03 AM] }
[6/4/2019 1:11:10 AM] Executing HTTP request: {
[6/4/2019 1:11:10 AM]   "requestId": "828f34bf-30b4-40fd-89cf-36cb205e1690",
[6/4/2019 1:11:10 AM]   "method": "GET",
[6/4/2019 1:11:10 AM]   "uri": "/api/inventory"
[6/4/2019 1:11:10 AM] }
[6/4/2019 1:11:10 AM] Function started (Id=2f14da90-fa89-4a5d-90e5-eda3e117ff73)
[6/4/2019 1:11:10 AM] Executing 'GetInventoryBySku' (Reason='This function was programmatically called via the host APIs.', Id=2f14da90-fa89-4a5d-90e5-eda3e117ff73)
[6/4/2019 1:11:10 AM] C# HTTP trigger function (GetInventoryBySku received a request.
[6/4/2019 1:11:10 AM] Internal Id: 4fae9d60-c0ac-4df3-870a-c4a9e9f91d0b
[6/4/2019 1:11:10 AM] Function completed (Success, Id=2f14da90-fa89-4a5d-90e5-eda3e117ff73, Duration=11ms)
[6/4/2019 1:11:10 AM] Executed 'GetInventoryBySku' (Succeeded, Id=2f14da90-fa89-4a5d-90e5-eda3e117ff73)
[6/4/2019 1:11:10 AM] Executed HTTP request: {
[6/4/2019 1:11:10 AM]   "requestId": "828f34bf-30b4-40fd-89cf-36cb205e1690",
[6/4/2019 1:11:10 AM]   "method": "GET",
[6/4/2019 1:11:10 AM]   "uri": "/api/inventory",
[6/4/2019 1:11:10 AM]   "authorizationLevel": "Anonymous",
[6/4/2019 1:11:10 AM]   "status": "OK"
[6/4/2019 1:11:10 AM] }
```

**Comment by lorddev** [comment] 2019-06-04 01:45
> I started the program and ran that method 3 times and you will notice in the attached log that the line "Internal Id: 4fae9d60-c0ac-4df3-870a-c4a9e9f91d0b" appears 3 times. This indicates that the same instance of dbcontext is being provided each time that the function executes.

This is the bug, I think. I want it to work like InstancePerRequest does in ASP.NET. I don't want multiple HTTP requests to use the same instance.

**Comment by rawrspace** [comment] 2019-06-04 02:01
Gotcha. Now I understand. I will hop on again tomorrow night and hopefully get an answer for you. Sorry for the delay.

**Comment by rawrspace** [comment] 2019-06-04 02:03
Just to clarify what you said. You just want a new dbcontext for each http request? That should be the default behavior when you simply register type as interface like in the examples of the documentation.

**Comment by lorddev** [comment] 2019-06-04 04:15
Yes. I didn't know it was the default because I had become used to using `InstancePerRequest()` in ASP.NET. I was going by [this SO answer](https://stackoverflow.com/a/23356038/16454) which said that `InstancePerLifetimeScope()` would do the same thing (it's one of the top results if you Google _instanceperlifetimescope vs instanceperrequest_). So I assumed it's a bug since it's not behaving that way.

**Comment by rawrspace** [comment] 2019-06-04 12:07
Can you try registering them the same way as in the README.md where you just say `builder.RegisterType<MyType>().As<IInterface>();` and if that doesn't work then I can continue helping.

**Comment by lorddev** [comment] 2019-06-04 16:28
Well, now i'm getting
> The underlying provider failed on Open. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. 

Which is not a fault with AzureFunctions.Autofac

**Comment by lorddev** [comment] 2019-06-04 18:13
It ran much more smoothly when I wrapped everything in IDisposable but I still got this _one time_: 
> A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.

**Comment by lorddev** [comment] 2019-06-04 18:20
Looks like that was due to another instance of the old code writing to the logs. Closing this, but it might be worth updating the documentation?

**Comment by rawrspace** [comment] 2019-06-04 22:32
Glad you figured it out. I'll work on updating the documentation soon.

**Closed as completed** 2019-06-04 22:32 UTC
Labels: question

**Comment by lorddev** [comment] 2019-08-22 20:12
@vandersmissenc I have refactored my code to remove InstancePerLifetimeScope() and wrapped EVERYTHING in IDisposable pattern. I'm getting this:

```
The  underlying provider failed on Open. Timeout expired.  The timeout  period elapsed prior to obtaining a connection from the pool.  This may  have occurred because all pooled connections were in use...
```

If I put InstancePerLifetimeScope back in, I end up with "object already disposed" exceptions.
