### ISSUE TITLE
Function NetCore doesn't work anymore with depency Injection (2.0.12050-alpha)

### ISSUE THREAD

**Issue by ppeau** [introtocomputerscience/azure-function-autofac-dependency-injection#23] opened 2018-08-31 03:59 UTC
Function NetCore doesn't work anymore with depency Injection. 
I've been able to replicate the issue with your own NetCoreExample.

Certainly due to the Azure Functions Runtime 2.0.12050-alpha NuGet package released Wednesday, August 29, 2018 

![autofac](https://user-images.githubusercontent.com/357328/44891814-634c5000-acaf-11e8-9a22-c86138a314a7.png)

**Comment by bcnzer** [comment] 2018-08-31 09:08
I've got the same issue

**Comment by rawrspace** [comment] 2018-08-31 10:27
Thanks for reporting. I saw their tweet yesterday about the new version. I'll try to have a look ASAP.

**Comment by bcnzer** [comment] 2018-08-31 10:32
This is the post with the breaking change information: https://github.com/Azure/app-service-announcements/issues/129

Let me know if I can give you a hand. I forked the code but couldn't immediately see what was is wrong and it's late here.

FWIW, I tried another DI NuGet library (similar to this one) and it too is broken. Wonder if they changed something with Autofac?

Thank you for looking into it

EDIT: When I pinned my AF tools to the previous version everything works again.

**Comment by rawrspace** [comment] 2018-08-31 13:21
I think I have an idea of why this doesn't work and I am following up on that. Unfortunately to get it to work I have to add some code that is unsupported by the .NET Framework webjobs package. My dilemma now is do I drop support for .NET Framework and call this v 4.0.0 of AzureFunctions.Autofac or is there a way to split the code so there are two different versions without having two seperate nuget packages. I don't know the answer to that yet.

**Comment by rawrspace** [comment] 2018-08-31 15:43
@bcnzer If you would be so kind as to test [Version 3.0.4-beta1](https://www.nuget.org/packages/AzureFunctions.Autofac/3.0.4-beta1) and let me know if the issue is resolved for you that would be great. It resolved it for me but I would like a second opinion.

**Comment by rawrspace** [comment] 2018-08-31 15:52
Reopened to get the feedback before I remove it from beta.

**Comment by bcnzer** [comment] 2018-08-31 19:41
@vandersmissenc It's working! Woo hoo!

I updated my project to Microsoft.NET.Sdk.Functions to v1.0.19, used 3.0.4-beta1 and then used the latest AF tools. It all sprung into life. No errors. 

Really appreciate you jumping onto this quickly. If you were nearby I'd buy you a beer.

**Comment by rawrspace** [comment] 2018-08-31 20:11
Thanks for reporting it. Closing this out. Full release 3.0.4 is publishing on NuGet now.

**Closed as completed by rawrspace** 2018-08-31 20:11 UTC
Labels: bug, verified, fixed
